### PR TITLE
bump bioregistry version

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by cmungall** [comment]
The fix for this is in #61

**Comment by sierra-moxon** [comment]
ok to close this in favor of the most recent PR that bumps up bioregistry (allowing it to float as long as the floating version is a patch revision)?

**Comment by cmungall** [comment]
Yep!

**Comment by turbomam** [comment]
resolved by 
- https://github.com/linkml/schemasheets/pull/96

**Pull request closed without merging**
